spring:
  datasource:
    url: jdbc:mysql://mysql:3306/db?useSSL=false
    password: password
    username: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create
    database: MYSQL
    show-sql: true
    generate-ddl: true